### ISSUE TITLE
File missing issue

### ISSUE THREAD

**Issue by Burt-code** [zhangzc21/PetsGAN#1]
When I clone this project and try to reproduce it, I found that I could not find the vgg file that can be imported from Pretrained directory, so the inversion.py file cannot work as I wish, whereas I have followed the README guidance and downloading pertained files and put them into Pretrained directory. Did the corresponding file be removed to another place or it was missing somehow? Would it be fixed in the near future? 
BTW, would there be any instructions in reproducing this project? 
Thanks a lot.

**Comment by arad2022** [comment]
> When I clone this project and try to reproduce it, I found that I could not find the vgg file that can be imported from Pretrained directory, so the inversion.py file cannot work as I wish, whereas I have followed the README guidance and downloading pertained files and put them into Pretrained directory. Did the corresponding file be removed to another place or it was missing somehow? Would it be fixed in the near future? BTW, would there be any instructions in reproducing this project? Thanks a lot.

Hi, did you find any solution for this problem ? 
I can't find test.py for load pretrained models. Did you use pretrained files for test the model?
@zhangzc21 @Burt-code

**Comment by zhangzc21** [comment]
I'm so sorry for I just noticed this issue and my cursoriness. The file vgg.py has been uploaded.  The detailed readme will be prepared after a month since there are lots of things to do in recent days, however, I believe you can run the project using the main.py.  Welcome to email me if you have more problems.
