### ISSUE TITLE
Appendix for this paper

### ISSUE THREAD

**Issue by junseokoh1** [zhangzc21/PetsGAN#3]
Hi i'm interested in your research. But i can't find appendix for this paper at AAAI and arXiv page.
Is there any ways to get appendix for this paper?

**Comment by zhangzc21** [comment]
Hi, @junseokoh1, thanks for your interest and reminder. I just noticed that AAAI proceedings do not provide supplementary materials like other conferences. I will upload the appendix as far as possible, please wait for some time.

**Comment by zhangzc21** [comment]
Hi, @junseokoh1.  I have uploaded the [PetsGAN_SM.pdf](https://github.com/zhangzc21/PetsGAN/blob/main/PetsGAN_SM.pdf),  very sorry for your waiting.
